### ISSUE TITLE
Farmer and Admin dashboard error

### ISSUE THREAD

**Issue by omkar-79** [FoodPrintLabs/foodprint#198]
When trying to access Admin and Farmer dashboard, it is showing " Error:
Unexpected Error occured"
![image](https://user-images.githubusercontent.com/76155602/227766272-a192dea4-ff53-48d4-849f-830918a5749e.png)
Kindly resolve this issue.

**Comment by omkar-79** [comment]
This is issue was caused due to absence of 'harvest_image_url' column in 'foodprint_harvest' table. This issued resolved for me by deleting the 'harvest_image_url' line from 'models/foodprint_harvest.js'.

**Comment by jajukajulz** [comment]
We have migrated to use file hosting service for images instead of storing in the DB and so `harvest_image_url` is required. This is fixed in current Dev branch and soon landing on Master
